# Generated by Django 4.0.4 on 2022-05-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Author_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Pen_Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Is_Disabled', models.BooleanField()),
                ('Created_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Sales_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Recepient_Name', models.CharField(max_length=255)),
                ('Recepient_Email', models.CharField(max_length=255)),
                ('Book_Title', models.CharField(max_length=255)),
                ('Quantity', models.PositiveIntegerField()),
                ('Price_Per_Unit', models.PositiveIntegerField()),
                ('Price_Total', models.PositiveIntegerField()),
                ('Created_Time', models.DateTimeField()),
                ('Author_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Summary', models.CharField(max_length=255)),
                ('Stock', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Cover_URL', models.CharField(max_length=255)),
                ('Created_Time', models.DateTimeField()),
                ('Author_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.author')),
            ],
        ),
    ]
