# Generated by Django 4.0.4 on 2022-05-14 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Password',
            field=models.CharField(default='1', max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
