# Generated by Django 4.0.4 on 2022-05-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_created_time_alter_author_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author_ID',
            field=models.ForeignKey(db_column='Author_ID', on_delete=django.db.models.deletion.RESTRICT, to='app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Cover_URL',
            field=models.ImageField(upload_to='bookstore/app/uploads/'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Author_ID',
            field=models.ForeignKey(db_column='Author_ID', on_delete=django.db.models.deletion.RESTRICT, to='app.author'),
        ),
    ]
